FLOUR = "flour"
FATS = "fats"
SWEETENERS = "sweeteners"
FLAVORINGS = "flavorings"
LIQUIDS = "liquids"
LEAVENERS = "leaveners"
ADDIN = "add-ins"
STABILIZERS = "stabilizers"
TOPPINGS = "toppings"
SALTS = "salts"

CUP = "cup"
OUNCE = "oz"
TSP = "tsp"
TBSP = "tbsp"

MAXIMUMS = {
    FLOUR : 3,
    FATS : 2,
    SWEETENERS : 1,
    LEAVENERS : 4 
}

CATEGORIES = [FLOUR, FATS, SWEETENERS, FLAVORINGS, SALTS,
              LIQUIDS, LEAVENERS, ADDIN, STABILIZERS, TOPPINGS]

__all__ = [FLOUR, FATS, SWEETENERS, FLAVORINGS, LIQUIDS, LEAVENERS, ADDIN,
STABILIZERS, TOPPINGS, SALTS, CUP, OUNCE, TSP, TBSP, CATEGORIES]