DRY_BASES = "dry_base"
WET_BASES = "wet_base"
SWEETENERS = "sweetener"
FLAVORINGS = "flavoring"
SPICES = "spices"
FILLINGS = "filling"
LEAVENERS = "leavener"
TOPPINGS = "toppings"

CUP = "cup"
OUNCE = "oz"
TSP = "tsp"
TBSP = "tbsp"